### ISSUE TITLE
Starting ImageJ from Matlab: Java Swing Look and Feel service error

### ISSUE THREAD

**Issue by akshay-vedi** [imagej/imagej-matlab#28]
Hello all,
I am facing a problem in launching ImageJ from Matlab using IJM. I am getting the following errors on invoking ImageJ with window pop up as false and true respctively.

>> addpath('/home/wolfgang/Downloads/fiji-linux64/Fiji.app/scripts/');
>> javaaddpath('/home/wolfgang/Downloads/fiji-linux64/Fiji.app/jars/ij-1.53t.jar');
>> ImageJ(false);
Error using ImageJ
Java exception occurred:
java.lang.NullPointerException
	at net.imagej.matlab.ImageJMATLAB.disableIJExit(ImageJMATLAB.java:247)
	at net.imagej.matlab.ImageJMATLAB.launch(ImageJMATLAB.java:156)
	at net.imagej.matlab.ImageJMATLAB.start(ImageJMATLAB.java:105)
 
>> ImageJ(true);
Error using ImageJ
Java exception occurred:
java.lang.IllegalArgumentException: Invalid look and feel:
	at org.scijava.ui.swing.laf.SwingLookAndFeelService.setLookAndFeel(SwingLookAndFeelService.java:124)
	at org.scijava.ui.swing.laf.SwingLookAndFeelService.initLookAndFeel(SwingLookAndFeelService.java:85)
	at net.imagej.legacy.IJ1Helper.setVisible(IJ1Helper.java:324)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:132)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:166)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:151)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:110)
	at net.imagej.Main.launch(Main.java:47)
	at net.imagej.matlab.ImageJMATLAB.launch(ImageJMATLAB.java:151)
	at net.imagej.matlab.ImageJMATLAB.start(ImageJMATLAB.java:105)
	at net.imagej.matlab.ImageJMATLAB.start(ImageJMATLAB.java:92)
Caused by: java.lang.ClassNotFoundException:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:1879)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:582)
	at org.scijava.ui.swing.laf.SwingLookAndFeelService.setLookAndFeel(SwingLookAndFeelService.java:118)
	... 10 more

I updated the ImageJ plugins URLs. I also referenced matlab and ImageJ to same java versions (1.8.0_202 and 1.8.0_322). I’m using Matlab version 2022b and ImageJ 1.53t on Ubuntu 22.04.1 LTS.

Any kind of help in fixing this is really appreciated. Please let me know if you need any further information.

Thanks!

**Comment by akshay-vedi** [comment]
Hello, thanks for your prompt reply. I am not very experienced with compiling java files. Could you please let us know how I can make these changes in the imageJ. I am thinking that I need to create a new jar file for scijava.ui.swing and replace the jar file in imageJ with this new one. If that's the case, could you please send us the updated jar file, that would be extremely helpful. Thanks again!

**Comment by ctrueden** [comment]
Oh, I didn't want to close this quite yet, until you confirm that these changes fix the issues for you, @akshay-vedi. I am concerned that I fixed the *symptoms* of your issue, but that your configuration may actually be incorrect. I have not tested ImageJ-MATLAB since we added the FlatLaf support for HiDPI displays, so it may be that it simply does not work with MATLAB and the changes I made to guard against problems are necessary, and all will work for you now apart from the new Look & Feel. However, it might instead be the case that your ImageJ is not correct when it starts up, e.g. missing the [ImageJ Legacy](https://imagej.net/libs/imagej-legacy) support. Please let us know how it goes!

**Comment by akshay-vedi** [comment]
@ctrueden It works!! Thanks a lot for your help :)
